### ISSUE TITLE
Error during getToken(), status 404

### ISSUE THREAD

**Issue by AMGMNPLK** [hokim-m/click-up-x-obsidian#18]
I am getting the following error when trying to use the Click-Up Sync plugin in Obsidian:

```
[plugin:click-up-sync:574 Error during getToken() Error: Request failed, status 404
    at new t (app.js:1:1977769)  
    at qG (app.js:1:1977961)
    at app.js:1:1978638
    at app.js:1:237056
    at Object.next (app.js:1:237161)
    at a (app.js:1:235879)]
```

## Steps to Reproduce
1. Installed the Click-Up Sync plugin in Obsidian 
2. Configured the plugin settings with my ClickUp API token
3. Tried to sync my tasks

## Expected Behavior 
The plugin should be able to authenticate and sync my ClickUp tasks into Obsidian.

## Actual Behavior
Getting a "Request failed, status 404" error when the plugin tries to get the access token. The full error is provided above.

Let me know if you need any other information to debug this issue. Looking forward to getting this resolved. Thank you!

**Comment by AMGMNPLK** [comment]
Hi, is this plugin abandoned?

**Comment by hokim-m** [comment]
Hi @AMGMNPLK 

Will check that. I wasn't using github as a primary repo for my projects and did not see at all.

**Comment by Zafarzz** [comment]
Hi @AMGMNPLK,bug  fixed, please update
