### ISSUE TITLE
502 Bad Gateway nginx/1.18.0 (Ubuntu)

### ISSUE THREAD

**Issue by AMGMNPLK** [hokim-m/click-up-x-obsidian#19]
After clicking up the sing button and select the workspace, I get this error:

502 Bad Gateway
nginx/1.18.0 (Ubuntu)

**Comment by looqingGood** [comment]
Also getting this issue 
<img width="855" alt="Screenshot 2024-07-21 at 1 28 42 PM" src="https://github.com/user-attachments/assets/10ea46ef-3602-452b-b5c1-9bd4d22ce559">

**Comment by rolanddutoit** [comment]
Yep, me too. The code is still in the URL, but pasting that code and then trying to continue it just hangs on "Loading..."

**Comment by Amina-Delali** [comment]
I am having the same issue here. So I tried the same steps as @AMGMNPLK , and I had the same results: the modal window of the login freezes : 
<img width="470" alt="image" src="https://github.com/user-attachments/assets/9ed384ed-b39f-4d42-85be-0b19a9085fb3">

**Comment by Redster1** [comment]
I get the same issue. When I paste the code in to sign in, it loads indefinitely and the condole provides this error: 
![image](https://github.com/user-attachments/assets/b16f0389-336e-4cc2-835f-7061ceaf2a08)

**Comment by CCampanini** [comment]
Same issue here "502 Bad Gateway". For the moment, I decided to opt for [Todoist](https://jamiebrynes7.github.io/obsidian-todoist-plugin/docs/overview/) because there is working plugin that connects it to Obsidian.
Thank you anyway @hokim-m for sharing your work

**Comment by MilesRomney** [comment]
Same issue.

**Comment by hokim-m** [comment]
@CCampanini  @MilesRomney 
Do you still receive the error?

Looks like an issue with the server.

P.S. Sorry for late response for some reason I wasn't getting any notification about issues and comments

**Comment by Redster1** [comment]
Hey, @hokim-m!  Thanks for getting back to us!  Currently, I no longer get the bad gateway issue, but I now get this error: 
![image](https://github.com/user-attachments/assets/ee082047-8a81-4c48-97f2-6193e42a2fa3)

Let me know if there's anything else you'd like me to send you.  Looking at the console, I am not sure what would be helpful.

**Comment by Zafarzz** [comment]
Hi @Redster1, fixed, please update plugin

**Comment by Redster1** [comment]
Heyo! It works!
