### ISSUE TITLE
no redirect

### ISSUE THREAD

**Issue by Arhidiz** [hokim-m/click-up-x-obsidian#20]
<img width="602" alt="image" src="https://github.com/user-attachments/assets/61be7836-2c01-43fc-b062-7fbde824c838">
no redirect/ What is magic button?

**Comment by hokim-m** [comment]
Can you update the uplugin and try once more?
We've shipped new version fixing previous issues

**Comment by theperfectwill** [comment]
> Can you update the uplugin and try once more? We've shipped new version fixing previous issues

@hokim-m Just thought I would comment and update regarding this. I tried it just now and the redirect and validation worked for me.
